// Auto-generated by Cortex. Emits N bells to mark a session's state:
// 1 = finished a turn ("done"), 2 = started a prompt ("working"), 3 = waiting on
// your input ("waiting"). Output is Claude Code hook JSON.
const arg = process.argv[2];
const bells = arg === "waiting" ? 3 : arg === "working" ? 2 : 1;
process.stdout.write('{"terminalSequence":"' + "\\u0007".repeat(bells) + '"}');
